#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\IndexController::index
unauthorized:
    path: /api/unauthorized
    controller: App\Controller\IndexController::unauthorized
