#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check
index:
    path: /
    controller: App\Controller\IndexController::index
unauthorized:
    path: /api/unauthorized
    controller: App\Controller\IndexController::unauthorized
