#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check
index:
    path: /
    controller: App\Controller\IndexController::index
unauthorized:
    path: /api/unauthorized
    controller: App\Controller\IndexController::unauthorized
project-get:
    path: /api/project
    methods: [GET]
    controller: App\Controller\ProjectController::index
project-create:
    path: /api/project
    methods: [POST]
    controller: App\Controller\ProjectController::create
project-update:
    path: /api/project/{id}
    methods: [PUT]
    controller: App\Controller\ProjectController::update
project-delete:
    path: /api/project/{id}
    methods: [DELETE]
    controller: App\Controller\ProjectController::delete